#!/usr/bin/env python
import os
import sys

def _run_chiplotle( ):
   try:
      file = sys.argv[1]
   except IndexError:
      file = ''

   python_code  = "print '+--------------+'; "
   python_code += "print '|  Chiplotle!  |'; "
   python_code += "print '+--------------+'; "
   python_code += "import sys; "
   python_code += "sys.ps1 = 'chiplotle> '; " 
   python_code += "del sys;"
   python_code += "from chiplotle import *; "
   python_code += "plotter = instantiate_plotter( ); "

   os.system('''python -i %s -c "%s"''' % (file, python_code))


if __name__ == '__main__':
   _run_chiplotle( )
