#!/usr/bin/env python
import os
import sys

def _run_chiplotle( ):
   try:
      file = sys.argv[1]
   except IndexError:
      file = ''

   python_code  = "import sys; "
   python_code += "sys.ps1 = 'chiplotle> ';" 
   python_code += "del sys;"
   python_code += "from chiplotle import *; "
   python_code += "plotter = instantiate_plotter( );"
   os.system('''clear; python -i %s -c "%s"''' % (file, python_code))


if __name__ == '__main__':
   _run_chiplotle( )
